use_frameworks!

platform :ios, '12.0'

target 'MUXSDKImaListener_Tests' do
  pod 'Mux-Stats-Google-IMA', :path => '../'
  #pod 'Mux-Stats-Google-IMA', :git => 'https://github.com/muxinc/mux-stats-google-ima.git', :branch => 'nk/sc-35291/not-seeing-the-view-sessions-go-back-to-video'
  
  pod 'Specta'
    pod 'Expecta'
end
