use_frameworks!

target 'MUXSDKStatsGoogleIMAPlugin' do
  platform :ios, '12.0'
  pod 'Mux-Stats-AVPlayer', '3.4.2'
  pod 'Mux-Stats-Core', '4.6'
  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.16'
end

target 'MUXSDKStatsGoogleIMAPluginTVOS' do
  platform :tvos, '12.0'
  pod 'Mux-Stats-AVPlayer', '3.4.2'
  pod 'Mux-Stats-Core', '4.6'
  pod 'GoogleAds-IMA-tvOS-SDK', '~> 4.6'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                  config.build_settings['TVOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
